# This file overrides the main docker-compose.yml for the CI environment.
services:
  web:
    # In CI, we use an in-memory SQLite database for tests, so the `web`
    # service has no external dependencies. This saves significant memory.
    depends_on: {}