# This file overrides the main docker-compose.yml for the CI environment.
services:
  web:
    # In CI, we override the default command to prevent Gunicorn from starting.
    # This saves significant memory. The container is kept alive so we can
    # exec into it to run migrations and tests.
    command: tail -f /dev/null
    depends_on: {}