[pytest]
DJANGO_SETTINGS_MODULE = grateful_for.settings
python_files = tests.py test_*.py *_tests.py
addopts = --tb=short --reuse-db
cache_dir = /tmp/.pytest_cache
filterwarnings =
    ignore::UserWarning:dj_rest_auth.*
    ignore::DeprecationWarning:celery.*
    ignore::PendingDeprecationWarning:celery.*