# Generated by Django 5.2.4 on 2025-07-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/journal_photos/"
            ),
        ),
    ]
