name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy .env.example to .env
        run: cp example.env .env

      - name: Build and run containers
        run: docker compose up --build -d

      - name: Run tests
        run: docker compose exec web pytest